### ISSUE TITLE
Genome interoperability use case/demo use case

### ISSUE THREAD

**Issue by dwijnbergen** [ejp-rd-vp/DistributedAnalysis#39]
Use CARE-SM and Phenopackets to answer the question from Gijs

- [ ] Analysis of variants in genomes of patients to assist in profiling patients (federated genome interoperability case) (GDI use case)
- [ ]

**Comment by dwijnbergen** [comment]
Discuss the workflow in the coming week.

Focus update of metadata models on the parts of the models that we need.

**Comment by mroos** [comment]
Depracating this issue to continue with Issue #57
